### ISSUE TITLE
Review of Project Poposal

### ISSUE THREAD

**Issue by jasonseminara** [jmb1993/final_project#1]
@jmb1993, 

I think this is a great idea. I'd like to see some use cases and/or user stories that describe the site's interaction. This will help you nail down scope an maintain focus.

**Comment by jasonseminara** [comment]
Please respond to the above ASAP

**Comment by jmb1993** [comment]
Is this what you had in mind?

As a user, I want to be able to create an account to which I will save my favorite looks.
The looks on the site will be arranged by type of style - for example "streetwear", "casual", "office", "athlesuire", "black tie" etc so that users can access similar assortments of looks based on their personal taste or interest. It will be easy for a user to navigate around the different assortments, by using a navigation bar a the top of the page. 
When the user visits his page he can view the looks that he has saved and delete them if he chooses to do so.

**Comment by jasonseminara** [comment]
Yes! Approved.
